# Secret for MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==        # root
  mongo-root-password: ZXhhbXBsZQ==    # example
---
# PersistentVolumeClaim (RWO for Azure Disk)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteMany   # Must be RWO on Azure Disk
  resources:
    requests:
      storage: 1Gi
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          # Optional: remove readinessProbe if causing crash
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# WebApp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-webapp
  template:
    metadata:
      labels:
        app: dotnet-webapp
    spec:
      containers:
        - name: webapp
          image: udaypagidimari/dotnet-crud:latest
          ports:
            - containerPort: 5035
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MongoDB__DatabaseName
              value: ProductDB
            - name: MongoDB__ConnectionString
              value: "mongodb://root:example@mongodb:27017"
---
# WebApp Service
apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapp
spec:
  selector:
    app: dotnet-webapp
  ports:
    - port: 80
      targetPort: 5035
  type: LoadBalancer
