name: CI/CD to AKS using GitHub OIDC 
# correction 12  
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: adijaiswal/dotnet-mongo-crud
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:$TAG .

    - name: Push Docker Image
      run: docker push $IMAGE_NAME:$TAG

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl get ns webapps || kubectl create ns webapps
        kubectl apply -f dotnet-mongo-app.yaml -n webapps
